/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PomodoroTimer: typeof import('./src/components/PomodoroTimer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectMode: typeof import('./src/components/SelectMode.vue')['default']
    SettingsModal: typeof import('./src/components/SettingsModal.vue')['default']
  }
}
